#!/usr/bin/env node
var
  dbus= require( "dbus-native"),
  hello= require("./msg/hello"),
  List= require("./List")

var
  conn= dbus.createConnection()

conn.message(hello())

var l= List( conn, "org.PulseAudio1").then(console.log.bind(null, "works"))
