#!/usr/bin/env node
var
  dbus= require( "dbus-native"),
  hello= require("./msg/hello"),
  List= require("./List")

function connect(){
	var
	  conn= dbus.createConnection()
	conn.message(hello())
	return conn
}

function main(destination){
	destination= destination|| "org.freedesktop.DBus"
	var
	  conn= connect(),
	  l= List( conn, destination)
	l.then(JSON.stringify).then(console.log)
}

module.exports= main
module.exports.main= main
module.exports.connect= connect

if(require.main=== module){
	module.exports.main()
}
